/*
Assignment #3 - You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.

- Don't use any database, just store all the data in an array to store the todo list data (in-memory)
    Each todo has a title and a description. The title is a string and the description is a string.
    Each todo should also get an unique autogenerated id every time it is created
   
   The expected API endpoints are defined below,

1. GET `/todos` - Retrieve all todo items
   Description: Returns a list of all todo items.
   Response: 200 OK with an array of todo items in JSON format.
   Example: GET http://localhost:3000/todos

2. GET `/todos/:id` - Retrieve a specific todo item by ID
   Description: Returns a specific todo item identified by its ID.
   Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
   Example: GET http://localhost:3000/todos/123

3. POST `/todos` - Create a new todo item
   Description: Creates a new todo item.
   Request Body: JSON object representing the todo item.
   Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
   Example: POST http://localhost:3000/todos
   Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }

4. PUT `/todos/:id` - Update an existing todo item by ID
   Description: Updates an existing todo item identified by its ID.
   Request Body: JSON object representing the updated todo item.
   Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
   Example: PUT http://localhost:3000/todos/123
   Request Body: { "title": "Buy groceries", "completed": true }

5. DELETE `/todos/:id` - Delete a todo item by ID
   Description: Deletes a todo item identified by its ID.
   Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
   Example: DELETE http://localhost:3000/todos/123
   
- For any other route not defined in the server return 404
*/

// import express module using require function and store it in express variable
const express = require("express");

// create an express application using express function
const app = express();

// Middleware to parse JSON data in the request body
app.use(express.json());

// create an array to store the todo items
let todos = [];


// Route to get all todo items
app.get("/todos", (req, res) => {
    res.json(todos)
})


// Route to get a specific todo item by ID
app.get("/todos/:id", (req, res) => {

/* get the id from the request parameters and store it in id
    Extract id from URL
    Example: URL → /todos/5
    req.params.id → "5"
    parseInt → 5
*/const id = parseInt(req.params.id);

    // find the todo item with given item 
    const todo = todos.find((todo) => todo.id === id)
    // If the todo item is found, send it as a response
    if (todo) {
        res.json(todo);
    } else {

        // If the todo item is not found, send a 404 status code
        res.status(404).send("Todo item not found with id " + id);
    }
})

// Route to create a new todo item
app.post("/todos", (req, res) => {
    // get the title and description from the request body
    // const title = req.body.title;
    // const description = req.body.description;
    const { title, description } = req.body

    /* create a new todo item with an unique id
    If you have 2 todos → todos.length is 2 ,id = 2 + 1; // id = 3
If you have 3 todos → todos.length is 3 
So if the user sends:
Then:
title becomes "Buy milk"
description becomes "From the supermarket"
{
  id: 3,
  title: "Buy milk",
  description: "From the supermarket"
}*/

    const todo = {
        id: todos.length + 1,
        title: title,
        description: description,
        done:false
    }

    // add the new todo item to the todos array
    todos.push(todo)


    // send the todo item as a response with status code 201
    res.status(201).json(todo)

})
// Route to update an existing todo item by ID
// Route to update an existing todo item by ID
app.put("/todos/:id", (req, res) => {
    // get the id from the request parameters and store it in id
    const id = parseInt(req.params.id)

    // find the todo item with the given id
    const todo = todos.find((todo) => todo.id === id)

// If I want to update the date field of  todo,I should destructure it from req.body like this:
// const { title, description, date } = req.body;
// todo.title = title;
// todo.description = description;
// todo.date = date;  // update the date property
// todo.done = false; // if you want to reset completed status

    // If the todo item is found, update it with the new data
    if (todo) {
        // get the title and description from the request body
        const { title, description } = req.body;

        // update the todo item with the new data
        todo.title = title;
        todo.description = description;

        // send a response with the updated todo item
        res.json(todo);
    } else {
        // If the todo item is not found, send a 404 status code
        res.status(404).send("Todo item not found with id " + id);
    }

})
//mark as done when your todo completed
app.put("/todos/:id/done",(req,res)=>{
    const  id = parseInt(req.params.id)
    const todo = todos.find((todo) => todo.id === id)
    if(todo){
        todo.done =true; // ✔ mark as completed
        res.json(todo);        // return updated todo
    }else {
        res.status(404).send("odo item not found with id " + id)
    }

      
})
//make undo 
app.put("/todos/:id/undo",(req,res)=>{
    const id = parsetInt(req,params.id)
    const todo = todos.find((todo)=>todo.id === id)
    if(todo){
        todo.done = false;  // ✔ undo completed
        res.json(todo)
    }else {
        res.status(404).send("todo item not found with id " + id)
    }
})

// Route to delete a todo item by ID
app.delete("/todos/:id", (req, res) => {
    // get the id from the request parameters and store it in id
    const id = parseInt(req.params.id);

    // find the index of the todo item with the given id
    const index = todos.findIndex((todo) => todo.id === id);

    // If the todo item is found, delete it from the array
    if (index !== -1) {

        /* remove the todo item from the array ,array.splice(startIndex, deleteCount)
        First argument = position
        Second argument = how many items to delete */
        todos.splice(index, 1);

        // send a response with status code 200
        res.status(200).send("Todo deleted successfully with id " + id);
    } else {
        // If the todo item is not found, send a 404 status code
        res.status(404).send("Todo item not found with id " + id);
    }
});
// Route to handle any other route not defined in the server
/*app.use((req, res) => {
    res.status(404).send("Route Not Found");
});*/
app.all("*", (req, res) => {
    res.status(404).send("Route Not Found");
});

// Start the server on port 3000
app.listen(3000);